### ISSUE TITLE
Improve generation algorithm

### ISSUE THREAD

**Issue by Thenlie** [Thenlie/pathfinder#17]
# Refactor the maze generation algorithm to use recursive backtracking, rather than brute force. 

The style of the new maze will also be different. Instead of styling entire cells, only borders will be styled. This means every maze cell will be white, and the borders will determine where you can move. 

- [x] Move existing code to a new component. 
- [x] Refactor code to remove any unnecessary parts
- [x] Implement recursive back tracking
    - [x] Create stack
    - [x] Track visited cells
    - [x] Pop off stack when dead end
    - [x] End when every single cell is visited
- [x] Style borders accordingly
    - [x] Borders are drawn where cells are not linked (a move was not made from one cell to the other)

> NOTE: This will be made as an entirely new component since everything done on both front and back end will change. 

## Mockup

![image](https://user-images.githubusercontent.com/41388783/184505635-a66e1f6b-3dec-4df0-9620-bade7a004ae9.png)

**Comment by Thenlie** [comment]
❗ Branch created. Checkout with the command below ⬇️ 
```
git fetch origin
git checkout 17-generator/recursion
```
> NOTE: Be sure to merge main after using the command above.

**Comment by Thenlie** [comment]
@phillpeters Curious to hear your thoughts on this refactor I have been thinking about. 💭 💭 💭 

I think this framework makes the maze much more "maze-like" and should also be slightly quicker than the previous algorithm. It will change a large part of what we are doing since it will be a bit more difficult to represent these cells in a 2D array. Since every cell is technically available, we need to check walls (borders) instead of neighbor cells. I thought we might be able to use objects to store each cells data. Ex.
```js
let startCell = {
    top: 1,
    bottom: 0,
    left: 1,
    right: 0,
    visited: 0
}
```
Here we can set bits to 0 or 1 depending on if the cell has the specified border and as well if it has been visited. If we need more than a boolean we can always use integers. This example is for the first cell in the mockup maze.

**Comment by phillpeters** [comment]
I like this!  It definitely looks more "maze-like", and that will be even more obvious with large mazes. 

Would there be any merit to adding two more bits to the object for start and end cells?  This might be good for setting arbitrary starts and ends in our mazes. Ex.
```javascript
let startCell = {
    start: 1,
    end: 0,
    top: 1,
    bottom: 0,
    left: 1,
    right: 0,
    visited: 0
}
```
The 2D array approach still works though, right? Basically an array of arrays of objects?

Are your notes above the mockup pseudocode for generating the maze?  Because that looks like a great approach for solving the maze as well.  In fact, my sense is that this approach will make solving the maze easier, but generating it much harder.

**Comment by Thenlie** [comment]
@phillpeters 
---
> The 2D array approach still works though, right? Basically an array of arrays of objects?

Yes, the 2D array will still work and it will just be objects nested instead of integers. 

---

> Would there be any merit to adding two more bits to the object for start and end cells? 

I think this is a good idea but I have a couple hesitations. First, this could allow for more than one start and end cell, if implemented incorrectly. Second, every cell would contain two additional bits that are 99% of the time unused. 2 bits doesn't really matter, but it we can avoid it, may as well? One thought I had is just having a start and end cell value elsewhere stored in a variable:

```js
let startCell = { x: 0, y: 0 }
let endCell = { x: 100, y: 100 }
```

This should still give us the ability to set arbitrary start and end points, I really like that idea. 

---

> Are your notes above the mockup pseudocode for generating the maze? Because that looks like a great approach for solving the maze as well. In fact, my sense is that this approach will make solving the maze easier, but generating it much harder.

The notes above are just for generating the maze. Feel free to use them for inspiration, but I haven't thought much about solving, still just focused on generation.

**Comment by Thenlie** [comment]
# One more thing about Start and End cells

Since the new idea is using actual borders for walls, it will be possible to move to every single cell. This means we can set arbitrary start and finish points at any point after the maze is generated. So feel free to add those in as variables on your end so they can be dynamic later. 

@phillpeters
